CREATE TABLE IF NOT EXISTS blog_news(id INT AUTO_INCREMENT PRIMARY KEY , subject TEXT NOT NULL, body TEXT NOT NULL , releasedate DATETIME NOT NULL , author INT );
CREATE TABLE IF NOT EXISTS blog_user(id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, permission INT DEFAULT 0, displayname VARCHAR(50) UNIQUE);
CREATE TABLE IF NOT EXISTS blog_token(id INT AUTO_INCREMENT PRIMARY KEY, token char(26) NOT NULL UNIQUE, userId int NOT NULL, expire DATETIME);
CREATE TABLE IF NOT EXISTS blog_drafts(id INT AUTO_INCREMENT PRIMARY KEY, subject TEXT, body TEXT, author INT );